name: Publish Docker Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - vmagent
          - victoria-server
          - vmalert
          - victoria-logs

    steps:
      # Шаг 1: Клонировать репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Шаг 2: Вывести структуру репозитория
      - name: List files in the repository
        run: ls -R

      # Шаг 3: Выполнить вход в GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Шаг 4: Извлечь имя ветки или тега
      - name: Extract branch or tag name
        id: extract_branch
        run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV

      # Шаг 5: Собрать Docker-образ
      - name: Build Docker image
        run: |
          cd ${{ matrix.image }}
          docker build -t ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ env.branch_name }} .

      # Шаг 6: Пометить образ как latest
      - name: Tag Docker image as latest
        run: |
          docker tag ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ env.branch_name }} ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest

      # Шаг 7: Опубликовать образ
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ env.branch_name }}
          docker push ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest