name: Publish Docker Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - vmagent
          - victoria-server
          - vmalert

    steps:
      # Шаг 1: Вход в GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Шаг 2: Извлечение имени ветки или тега
      - name: Extract branch or tag name
        id: extract_branch
        run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV

      # Шаг 3: Сборка Docker-образа
      - name: Build Docker image
        run: |
          cd ${{ matrix.image }}
          docker build -t ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ env.branch_name }} .

      # Шаг 4: Пометка образа как latest
      - name: Tag Docker image as latest
        run: |
          docker tag ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ env.branch_name }} ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest

      # Шаг 5: Публикация образа
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ env.branch_name }}
          docker push ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest